import { readFile } from "node:fs/promises";
import path from "node:path";

export type DeployCommitEntry = {
  hash: string;
  shortHash: string;
  authorName: string;
  authoredAt: string;
  subject: string;
  body: string;
};

export type LatestDeployUpdate = {
  app: string;
  branch: string;
  release: string;
  appliedAt: string;
  commit: string;
  shortCommit: string;
  previousCommit: string | null;
  commits: DeployCommitEntry[];
};

function getLatestDeployUpdatePath(): string {
  const override = (process.env.DEPLOY_UPDATES_FILE || "").trim();
  if (override) {
    return override;
  }

  // deploy.sh writes this file into shared data, which is symlinked into each release as `.data`.
  return path.join(process.cwd(), ".data", "deploy", "latest-deploy-update.json");
}

/**
 * Reads the latest deploy metadata generated by deploy.sh for admin changelog visibility.
 */
export async function readLatestDeployUpdate(): Promise<LatestDeployUpdate | null> {
  try {
    const raw = await readFile(getLatestDeployUpdatePath(), "utf8");
    const parsed = JSON.parse(raw) as Partial<LatestDeployUpdate> | null;
    if (!parsed || typeof parsed !== "object") {
      return null;
    }
    if (!parsed.commit || !parsed.appliedAt || !Array.isArray(parsed.commits)) {
      return null;
    }

    return {
      app: String(parsed.app || "melbourne-guitar-school"),
      branch: String(parsed.branch || "main"),
      release: String(parsed.release || ""),
      appliedAt: String(parsed.appliedAt),
      commit: String(parsed.commit),
      shortCommit: String(parsed.shortCommit || String(parsed.commit).slice(0, 7)),
      previousCommit: parsed.previousCommit ? String(parsed.previousCommit) : null,
      commits: parsed.commits
        .map((entry) => ({
          hash: String((entry as DeployCommitEntry).hash || ""),
          shortHash: String((entry as DeployCommitEntry).shortHash || ""),
          authorName: String((entry as DeployCommitEntry).authorName || ""),
          authoredAt: String((entry as DeployCommitEntry).authoredAt || ""),
          subject: String((entry as DeployCommitEntry).subject || ""),
          body: String((entry as DeployCommitEntry).body || "")
        }))
        .filter((entry) => entry.hash && entry.subject)
    };
  } catch {
    return null;
  }
}
