#!/usr/bin/expect -f
set timeout 60
set password "d3anth0ms0n"
spawn scp /home/grahf/jon/melbourne-guitar-school/deploy/maintenance.sh grahf@melbourneguitarschool.com.au:~/melbourne-guitar-school/deploy/maintenance-remote-test.sh
expect {
    "Are you sure you want to continue connecting" {
        send "yes\r"
        exp_continue
    }
    "password:" {
        send "$password\r"
    }
}
expect eof
