import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";

import { requireOwnerFromRequest } from "@/lib/admin-route";
import { jsonUnexpectedError } from "@/lib/api-errors";
import { prisma } from "@/lib/db";
import { sendEmail } from "@/lib/email/service";
import { customerPortalCredentialTemplate } from "@/lib/email/templates";
import { getStudentPortalLoginUrl } from "@/lib/env";
import {
  revealPortalPasswordForAdmin,
  rotatePortalCredential
} from "@/lib/student-portal/credentials";

type Params = {
  params: Promise<{
    id: string;
  }>;
};

const mutationSchema = z.object({
  action: z.enum(["reveal", "regenerate"])
});

/**
 * Returns portal credential metadata for one customer (without revealing password).
 */
export async function GET(request: NextRequest, { params }: Params) {
  const admin = await requireOwnerFromRequest(request);
  if (!admin) {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  }

  const { id } = await params;
  const customer = await prisma.customer.findUnique({
    where: {
      id
    },
    include: {
      portalCredential: true
    }
  });
  if (!customer) {
    return NextResponse.json({ error: "Customer not found." }, { status: 404 });
  }

  return NextResponse.json({
    credential: customer.portalCredential
      ? {
          id: customer.portalCredential.id,
          generatedAt: customer.portalCredential.generatedAt.toISOString(),
          rotatedAt: customer.portalCredential.rotatedAt?.toISOString() || null,
          isActive: customer.portalCredential.isActive
        }
      : null
  });
}

/**
 * Reveals or regenerates portal credentials for admin support workflows.
 */
export async function POST(request: NextRequest, { params }: Params) {
  try {
    const admin = await requireOwnerFromRequest(request);
    if (!admin) {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }

    const body = await request.json().catch(() => null);
    const parsed = mutationSchema.safeParse(body);
    if (!parsed.success) {
      return NextResponse.json({ error: "Invalid portal credential action." }, { status: 400 });
    }

    const { id } = await params;
    const customer = await prisma.customer.findUnique({
      where: {
        id
      }
    });
    if (!customer || customer.isArchived) {
      return NextResponse.json({ error: "Customer not found." }, { status: 404 });
    }

    if (parsed.data.action === "reveal") {
      // Reveal uses a local catch because support-style "no credential exists" errors are domain
      // errors that should return a user-facing JSON response instead of the generic 500 wrapper.
      try {
        const result = await revealPortalPasswordForAdmin({
          customerId: customer.id,
          actorId: admin.id,
          details: `Portal password revealed by admin (${admin.email}).`
        });
        return NextResponse.json({
          password: result.password,
          credential: {
            id: result.credential.id,
            generatedAt: result.credential.generatedAt.toISOString(),
            rotatedAt: result.credential.rotatedAt?.toISOString() || null,
            isActive: result.credential.isActive
          }
        });
      } catch (error) {
        return NextResponse.json(
          { error: error instanceof Error ? error.message : "Unable to reveal portal password." },
          { status: 404 }
        );
      }
    }

    // Regenerate falls through to the outer unexpected-error wrapper for normalized 500 handling.
    const result = await rotatePortalCredential({
      customerId: customer.id,
      actorId: admin.id,
      details: `Portal password regenerated by admin (${admin.email}).`
    });

    const responsePayload = {
      password: result.generatedPassword,
      credential: {
        id: result.credential.id,
        generatedAt: result.credential.generatedAt.toISOString(),
        rotatedAt: result.credential.rotatedAt?.toISOString() || null,
        isActive: result.credential.isActive
      },
      created: result.created
    };

    let emailStatus: "sent" | "queued_no_smtp" | "failed" | "suppressed" | "skipped" = "skipped";
    let emailMessage = "Portal password regenerated. Customer email was skipped because no email address is saved.";

    if (customer.email.trim()) {
      const template = customerPortalCredentialTemplate({
        name: customer.fullName,
        loginUrl: getStudentPortalLoginUrl(),
        password: result.generatedPassword
      });
      try {
        const emailResult = await sendEmail({
          to: customer.email,
          subject: template.subject,
          html: template.html,
          notification: {
            triggerMode: "manual"
          }
        });
        emailStatus = emailResult.status;
        emailMessage =
          emailResult.status === "sent"
            ? "Portal password regenerated and login email sent to the customer."
            : emailResult.status === "queued_no_smtp"
              ? "Portal password regenerated. Login email was queued because no live email provider is configured."
              : `Portal password regenerated, but the login email failed to send${emailResult.error ? `: ${emailResult.error}` : "."}`;
      } catch (error) {
        const message = error instanceof Error ? error.message : "Unknown error";
        return NextResponse.json({
          ...responsePayload,
          partial: true,
          emailStatus: "failed",
          emailMessage: `Portal password regenerated, but the login email failed to send: ${message}`
        });
      }
    }

    return NextResponse.json({
      ...responsePayload,
      emailStatus,
      emailMessage
    });
  } catch (error) {
    return jsonUnexpectedError(error, "Unable to manage portal credential.");
  }
}
