import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";

import { requireAdminFromRequest } from "@/lib/admin-route";
import { jsonUnexpectedError } from "@/lib/api-errors";
import { prisma } from "@/lib/db";
import {
  revealPortalPasswordForAdmin,
  rotatePortalCredential
} from "@/lib/student-portal/credentials";

type Params = {
  params: Promise<{
    id: string;
  }>;
};

const mutationSchema = z.object({
  action: z.enum(["reveal", "regenerate"])
});

/**
 * Returns portal credential metadata for one customer (without revealing password).
 */
export async function GET(request: NextRequest, { params }: Params) {
  const admin = await requireAdminFromRequest(request);
  if (!admin) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { id } = await params;
  const customer = await prisma.customer.findUnique({
    where: {
      id
    },
    include: {
      portalCredential: true
    }
  });
  if (!customer) {
    return NextResponse.json({ error: "Customer not found." }, { status: 404 });
  }

  return NextResponse.json({
    credential: customer.portalCredential
      ? {
          id: customer.portalCredential.id,
          generatedAt: customer.portalCredential.generatedAt.toISOString(),
          rotatedAt: customer.portalCredential.rotatedAt?.toISOString() || null,
          isActive: customer.portalCredential.isActive
        }
      : null
  });
}

/**
 * Reveals or regenerates portal credentials for admin support workflows.
 */
export async function POST(request: NextRequest, { params }: Params) {
  try {
    const admin = await requireAdminFromRequest(request);
    if (!admin) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const body = await request.json().catch(() => null);
    const parsed = mutationSchema.safeParse(body);
    if (!parsed.success) {
      return NextResponse.json({ error: "Invalid portal credential action." }, { status: 400 });
    }

    const { id } = await params;
    const customer = await prisma.customer.findUnique({
      where: {
        id
      }
    });
    if (!customer || customer.isArchived) {
      return NextResponse.json({ error: "Customer not found." }, { status: 404 });
    }

    if (parsed.data.action === "reveal") {
      try {
        const result = await revealPortalPasswordForAdmin({
          customerId: customer.id,
          actorId: admin.id,
          details: `Portal password revealed by admin (${admin.email}).`
        });
        return NextResponse.json({
          password: result.password,
          credential: {
            id: result.credential.id,
            generatedAt: result.credential.generatedAt.toISOString(),
            rotatedAt: result.credential.rotatedAt?.toISOString() || null,
            isActive: result.credential.isActive
          }
        });
      } catch (error) {
        return NextResponse.json(
          { error: error instanceof Error ? error.message : "Unable to reveal portal password." },
          { status: 404 }
        );
      }
    }

    const result = await rotatePortalCredential({
      customerId: customer.id,
      actorId: admin.id,
      details: `Portal password regenerated by admin (${admin.email}).`
    });
    return NextResponse.json({
      password: result.generatedPassword,
      credential: {
        id: result.credential.id,
        generatedAt: result.credential.generatedAt.toISOString(),
        rotatedAt: result.credential.rotatedAt?.toISOString() || null,
        isActive: result.credential.isActive
      },
      created: result.created
    });
  } catch (error) {
    return jsonUnexpectedError(error, "Unable to manage portal credential.");
  }
}
