/**
 * Gmail API email service using OAuth2 authentication.
 * 
 * This module provides email sending via Gmail API, which bypasses
 * SMTP port restrictions commonly imposed by cloud providers like DigitalOcean.
 * 
 * SETUP REQUIREMENTS:
 * 1. Create a Google Cloud project at https://console.cloud.google.com
 * 2. Enable Gmail API for the project
 * 3. Create OAuth2 credentials (Desktop app)
 * 4. Run the token generation script: npx tsx scripts/generate-gmail-token.ts
 * 5. Add the generated tokens to .env
 * 
 * ENVIRONMENT VARIABLES:
 * - GMAIL_CLIENT_ID: OAuth2 client ID from Google Cloud
 * - GMAIL_CLIENT_SECRET: OAuth2 client secret from Google Cloud
 * - GMAIL_REFRESH_TOKEN: Refresh token generated by the script
 * - GMAIL_USER_EMAIL: The Gmail address to send from (e.g., lessonflow@gmail.com)
 */

import { prisma } from "@/lib/db";
import { logError, logEvent } from "@/lib/observability";
import { getGmailClient } from "@/lib/gmail/client";

type SendEmailInput = {
  to: string;
  subject: string;
  html: string;
  bcc?: string | string[];
  attachments?: Array<{
    filename: string;
    content: Buffer;
    contentType?: string;
  }>;
};

type SendEmailResult = {
  status: "sent" | "queued_no_smtp" | "failed";
  error?: string;
};

/**
 * Checks if Gmail API is configured with all required credentials.
 */
export function isGmailConfigured(): boolean {
  return !!(
    process.env.GMAIL_CLIENT_ID &&
    process.env.GMAIL_CLIENT_SECRET &&
    process.env.GMAIL_REFRESH_TOKEN &&
    process.env.GMAIL_USER_EMAIL
  );
}

/**
 * Encodes an email message in RFC 2822 format for Gmail API.
 *
 * We build the MIME message manually so the Gmail path supports the same HTML + attachment shape
 * used by the SMTP path without adding a second mail-composer abstraction.
 */
function encodeEmailMessage(
  from: string,
  to: string,
  bcc: string | string[] | undefined,
  subject: string,
  html: string,
  attachments?: Array<{
    filename: string;
    content: Buffer;
    contentType?: string;
  }>
): string {
  const boundary = `boundary_${Date.now()}_${Math.random().toString(36).slice(2)}`;
  
  // Build standards-compliant headers first; Gmail expects the final payload as a raw RFC 2822
  // message encoded with base64url.
  let email = [
    `From: ${from}`,
    `To: ${to}`,
    ...(Array.isArray(bcc)
      ? bcc.length > 0
        ? [`Bcc: ${bcc.join(", ")}`]
        : []
      : typeof bcc === "string" && bcc.trim()
        ? [`Bcc: ${bcc}`]
        : []),
    `Subject: =?UTF-8?B?${Buffer.from(subject).toString("base64")}?=`,
    "MIME-Version: 1.0",
    attachments && attachments.length > 0
      ? `Content-Type: multipart/mixed; boundary="${boundary}"`
      : "Content-Type: text/html; charset=UTF-8",
    "",
  ].join("\r\n");

  if (attachments && attachments.length > 0) {
    // Multipart message: HTML body first, then each attachment as a base64 part.
    email += `\r\n--${boundary}\r\n`;
    email += "Content-Type: text/html; charset=UTF-8\r\n";
    email += "Content-Transfer-Encoding: base64\r\n\r\n";
    email += Buffer.from(html).toString("base64");

    for (const attachment of attachments) {
      email += `\r\n--${boundary}\r\n`;
      email += `Content-Type: ${attachment.contentType || "application/octet-stream"}\r\n`;
      email += "Content-Transfer-Encoding: base64\r\n";
      email += `Content-Disposition: attachment; filename="${attachment.filename}"\r\n\r\n`;
      email += attachment.content.toString("base64");
    }

    email += `\r\n--${boundary}--`;
  } else {
    // Simple HTML email avoids multipart overhead when there are no attachments.
    email += "\r\n" + html;
  }

  // Gmail API expects URL-safe base64 without padding characters.
  return Buffer.from(email)
    .toString("base64")
    .replace(/\+/g, "-")
    .replace(/\//g, "_")
    .replace(/=+$/, "");
}

export async function sendGmailEmail(input: SendEmailInput): Promise<SendEmailResult> {
  if (!isGmailConfigured()) {
    return {
      status: "queued_no_smtp",
      error: "Gmail API is not configured. Missing required environment variables."
    };
  }

  const from = process.env.GMAIL_USER_EMAIL!;
  const rawMessage = encodeEmailMessage(from, input.to, input.bcc, input.subject, input.html, input.attachments);

  const gmail = getGmailClient();

  try {
    const response = await gmail.users.messages.send({
      userId: "me",
      requestBody: {
        raw: rawMessage,
      },
    });

    // Keep outbound email audit logging consistent with the SMTP implementation.
    await prisma.outboundEmail.create({
      data: {
        toEmail: input.to,
        subject: input.subject,
        htmlBody: input.html,
        status: "sent",
        provider: "gmail",
        externalId: response.data.id,
        source: "app"
      },
    }).catch((persistError) => {
      // Gmail already accepted the message, so we log audit persistence failures instead of
      // surfacing a false-negative delivery result to callers.
      logError("email.audit_persist_failed_after_gmail_send", persistError, {
        to: input.to,
        subject: input.subject,
        messageId: response.data.id
      });
    });

    logEvent("email.sent_gmail", { 
      to: input.to, 
      subject: input.subject, 
      messageId: response.data.id 
    });
    return { status: "sent" };
  } catch (error) {
    const message = error instanceof Error ? error.message : "Unknown Gmail API error";
    // Persist failures for admin troubleshooting and delivery audit visibility.
    await prisma.outboundEmail.create({
      data: {
        toEmail: input.to,
        subject: input.subject,
        htmlBody: input.html,
        status: "failed",
        provider: "gmail",
        source: "app",
        error: message,
      },
    });

    logError("email.gmail_failed", error, { to: input.to, subject: input.subject });
    return { status: "failed", error: message };
  }
}

/**
 * Gets the authenticated Gmail user's email address.
 * Useful for verifying the OAuth2 setup is working.
 */
export async function getGmailUserProfile(): Promise<string | null> {
  if (!isGmailConfigured()) {
    return null;
  }

  try {
    const gmail = getGmailClient();
    // Lightweight support probe used to verify OAuth configuration without sending an email.
    const profile = await gmail.users.getProfile({ userId: "me" });
    return profile.data.emailAddress || null;
  } catch (error) {
    logError("gmail.profile_failed", error);
    return null;
  }
}
